require("raxel.set")
require("raxel.keymaps")
require("raxel.colorscheme")
require("raxel.plugins.telescope")
require("raxel.plugins.undotree")
require("raxel.plugins.treesitter")
require("raxel.plugins.fugitive")
require("raxel.plugins.nvim-tree")
require("raxel.plugins.autopairs")
require("raxel.plugins.colorizer")
require("raxel.plugins.comment")
require("raxel.plugins.lualine")
require("raxel.plugins.harpoon")
require("raxel.plugins.zenmode")
-- require('raxel.plugins.barbar')
require("raxel.plugins.bufferline")
require("raxel.plugins.nvim-cmp")
require("raxel.plugins.lsp")
require("raxel.plugins.lspp.handlers").setup()
require("raxel.plugins.null-ls")
-- vim.cmd "lua ColorMyPencils()"
-- ColorMyPencils()
-- lsp
-- require("raxel.plugins.lspp.null-ls")
-- require('raxel.plugins.Tabnine')
-- require('raxel.plugins.lsp.lspconfig')
-- require('raxel.plugins.lsp.lspsaga')
-- require('raxel.plugins.lsp.mason')
-- require('raxel.plugins.lsp.null-ls')
